settings:
  input_device: Microsoft Sound Mapper - Input
trainer:
  active_profile: Kyt
  profiles:
    Kyt:
      profile: Kyt
      pishock_username: ''
      pishock_api_key: ''
      feature_focus: true
      feature_proximity: false
      feature_tricks: false
      feature_scolding: false
      difficulty: Normal
      names:
      - Kit
      - Kitsune
      - Umbreon
      - Pet
      command_words: []
      scolding_words:
      - Bad boy
      - Bad girl
      - Bad dog
      - Bad fox
      - Bad Umbreon
      - Shock
    a:
      profile: a
      pishock_username: ''
      pishock_api_key: ''
      feature_focus: false
      feature_proximity: false
      feature_tricks: true
      feature_scolding: false
      difficulty: Normal
      names: []
      command_words: []
      scolding_words: []
pet:
  pishock_username: ''
  pishock_api_key: ''
  feature_ear_tail: true
  feature_pronouns: true
