settings:
  input_device: Microsoft Sound Mapper - Input
trainer:
  active_profile: Kyt
  profiles:
    Kyt:
      profile: Kyt
      pishock_username: ''
      pishock_api_key: ''
      feature_focus: true
      feature_proximity: true
      feature_tricks: true
      feature_scolding: false
      difficulty: Normal
pet: {}
